### ISSUE TITLE
代码跑不通啊

### ISSUE THREAD

**Issue by Gong2Kun** [rancheng/Reconstruction_Pipeline#1]
::pair<Eigen::Matrix<double, 3, 1>, Eigen::Matrix<double, 3, 1> > >&, Eigen::Matrix3d&, Eigen::Vector3d&)’:
/home/gk/catkin_vox/src/VINS-RGBD/vins_estimator/src/initial/solve_5pts.cpp:258:24: error: missing template arguments before ‘(’ token
     Matrix3d rota = SO3(rvec.at<double>(0, 0), rvec.at<double>(1, 0), rvec.at<double>(2, 0)).matrix();

**Comment by rancheng** [comment]
用docker试试
